version: "3"
services:
  server:
    image: ankit23022/blog-app-apis:0.0.1-SNAPSHOT
    ports:
      - "9090:9090"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/blog_app_apis?useSSL=false&allowPublicKeyRetrieval=true
      - spring.datasource.username=admin
      - spring.datasource.password=admin
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0.28
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=blog_app_apis
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin

networks:
  springmysql-net: